[package]
name = "multitool"
version = "4.7.2"
description = "Professional-grade local toolbox"
authors = ["Visualize Build LLC"]
license = ""
repository = "https://github.com/noahfgarrett/Multitool"
default-run = "multitool"
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "multitool_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
