import type { FormDocument } from './types.ts'
import { createElement, createDocument } from './types.ts'

export interface FormTemplate {
  name: string
  description: string
  elementCount: number
  build: () => FormDocument
}

export const TEMPLATES: FormTemplate[] = [
  {
    name: 'Blank',
    description: 'A single blank page to start from scratch',
    elementCount: 0,
    build: () => createDocument({ title: 'New Form' }),
  },
  {
    name: 'Sign-in Sheet',
    description: 'Name, company, date, time in/out, and signature',
    elementCount: 7,
    build: () => createDocument({
      title: 'Sign-in Sheet',
      elements: [
        createElement('heading', 0, { id: 'si-h', label: 'Sign-in Sheet', x: 48, y: 40, width: 720, fontWeight: 'bold', fontSize: 24, textAlign: 'center' }),
        createElement('divider', 0, { id: 'si-d', x: 48, y: 90, width: 720 }),
        createElement('text-input', 0, { id: 'si-name', label: 'Name', x: 48, y: 120, width: 340 }),
        createElement('text-input', 0, { id: 'si-co', label: 'Company', x: 420, y: 120, width: 340 }),
        createElement('date', 0, { id: 'si-date', label: 'Date', x: 48, y: 190, width: 200 }),
        createElement('text-input', 0, { id: 'si-tin', label: 'Time In', x: 280, y: 190, width: 200 }),
        createElement('text-input', 0, { id: 'si-tout', label: 'Time Out', x: 510, y: 190, width: 200 }),
        createElement('signature', 0, { id: 'si-sig', label: 'Signature', x: 48, y: 270, width: 300 }),
      ],
    }),
  },
  {
    name: 'Contact Form',
    description: 'Full name, email, phone, and message fields',
    elementCount: 5,
    build: () => createDocument({
      title: 'Contact Form',
      elements: [
        createElement('heading', 0, { id: 'cf-h', label: 'Contact Information', x: 48, y: 40, width: 720, fontWeight: 'bold', fontSize: 22, textAlign: 'center' }),
        createElement('text-input', 0, { id: 'cf-name', label: 'Full Name', x: 48, y: 110, width: 720, required: true }),
        createElement('text-input', 0, { id: 'cf-email', label: 'Email', x: 48, y: 180, width: 340, required: true, placeholder: 'name@example.com' }),
        createElement('text-input', 0, { id: 'cf-phone', label: 'Phone Number', x: 420, y: 180, width: 340, placeholder: '+1 (555) 000-0000' }),
        createElement('textarea', 0, { id: 'cf-msg', label: 'Message', x: 48, y: 260, width: 720, height: 120 }),
      ],
    }),
  },
  {
    name: 'Work Order',
    description: 'Order number, date, requester, description, priority, and approval',
    elementCount: 9,
    build: () => createDocument({
      title: 'Work Order',
      elements: [
        createElement('heading', 0, { id: 'wo-h', label: 'Work Order', x: 48, y: 40, width: 720, fontWeight: 'bold', fontSize: 24, textAlign: 'center' }),
        createElement('divider', 0, { id: 'wo-d', x: 48, y: 90, width: 720 }),
        createElement('text-input', 0, { id: 'wo-num', label: 'Order Number', x: 48, y: 120, width: 200 }),
        createElement('date', 0, { id: 'wo-date', label: 'Date', x: 280, y: 120, width: 200 }),
        createElement('text-input', 0, { id: 'wo-req', label: 'Requested By', x: 48, y: 190, width: 340 }),
        createElement('text-input', 0, { id: 'wo-dept', label: 'Department', x: 420, y: 190, width: 340 }),
        createElement('textarea', 0, { id: 'wo-desc', label: 'Description of Work', x: 48, y: 260, width: 720, height: 120 }),
        createElement('radio', 0, { id: 'wo-pri', label: 'Priority', x: 48, y: 400, width: 200, height: 110, options: ['Low', 'Medium', 'High', 'Urgent'] }),
        createElement('textarea', 0, { id: 'wo-notes', label: 'Notes', x: 280, y: 400, width: 480, height: 110 }),
        createElement('signature', 0, { id: 'wo-sig', label: 'Approved By', x: 48, y: 540, width: 300 }),
      ],
    }),
  },
  {
    name: 'Inspection Form',
    description: 'Inspector, date, location, checklist items, findings, and result',
    elementCount: 11,
    build: () => createDocument({
      title: 'Inspection Report',
      elements: [
        createElement('heading', 0, { id: 'if-h', label: 'Inspection Report', x: 48, y: 40, width: 720, fontWeight: 'bold', fontSize: 24, textAlign: 'center' }),
        createElement('divider', 0, { id: 'if-d', x: 48, y: 90, width: 720 }),
        createElement('text-input', 0, { id: 'if-insp', label: 'Inspector Name', x: 48, y: 120, width: 340 }),
        createElement('date', 0, { id: 'if-date', label: 'Date', x: 420, y: 120, width: 200 }),
        createElement('text-input', 0, { id: 'if-loc', label: 'Location', x: 48, y: 190, width: 720 }),
        createElement('checkbox', 0, { id: 'if-c1', label: 'Equipment Operational', x: 48, y: 260, width: 300 }),
        createElement('checkbox', 0, { id: 'if-c2', label: 'Safety Guards in Place', x: 380, y: 260, width: 300 }),
        createElement('checkbox', 0, { id: 'if-c3', label: 'Area Clean & Organized', x: 48, y: 300, width: 300 }),
        createElement('checkbox', 0, { id: 'if-c4', label: 'PPE Available', x: 380, y: 300, width: 300 }),
        createElement('textarea', 0, { id: 'if-notes', label: 'Findings / Notes', x: 48, y: 350, width: 720, height: 120 }),
        createElement('radio', 0, { id: 'if-res', label: 'Result', x: 48, y: 490, width: 200, height: 90, options: ['Pass', 'Fail', 'Needs Attention'] }),
        createElement('signature', 0, { id: 'if-sig', label: 'Inspector Signature', x: 48, y: 600, width: 300 }),
      ],
    }),
  },
  // ── Construction Templates ─────────────────────────────────
  {
    name: 'Daily Field Report',
    description: 'Weather, crew count, work performed, delays, and superintendent sign-off',
    elementCount: 12,
    build: () => createDocument({
      title: 'Daily Field Report',
      elements: [
        createElement('heading', 0, { id: 'dfr-h', label: 'Daily Field Report', x: 48, y: 40, width: 720, fontWeight: 'bold', fontSize: 24, textAlign: 'center' }),
        createElement('divider', 0, { id: 'dfr-d', x: 48, y: 90, width: 720 }),
        createElement('date', 0, { id: 'dfr-date', label: 'Date', x: 48, y: 120, width: 200 }),
        createElement('text-input', 0, { id: 'dfr-proj', label: 'Project Name', x: 280, y: 120, width: 480 }),
        createElement('select', 0, { id: 'dfr-weather', label: 'Weather', x: 48, y: 190, width: 200, options: ['Clear', 'Cloudy', 'Rain', 'Snow'] }),
        createElement('number', 0, { id: 'dfr-temp', label: 'Temperature', x: 280, y: 190, width: 200, numberPrefix: '°F' }),
        createElement('number', 0, { id: 'dfr-crew', label: 'Crew Count', x: 510, y: 190, width: 200 }),
        createElement('textarea', 0, { id: 'dfr-work', label: 'Work Performed Today', x: 48, y: 270, width: 720, height: 120 }),
        createElement('textarea', 0, { id: 'dfr-delays', label: 'Delays / Issues', x: 48, y: 410, width: 720, height: 100 }),
        createElement('textarea', 0, { id: 'dfr-visitors', label: 'Visitor Log', x: 48, y: 530, width: 720, height: 100 }),
        createElement('divider', 0, { id: 'dfr-d2', x: 48, y: 650, width: 720 }),
        createElement('signature', 0, { id: 'dfr-sig', label: 'Superintendent Signature', x: 48, y: 670, width: 340 }),
      ],
    }),
  },
  {
    name: 'Safety Toolbox Talk',
    description: 'Topic, discussion points, attendee signatures, and next meeting topic',
    elementCount: 13,
    build: () => createDocument({
      title: 'Safety Toolbox Talk',
      elements: [
        createElement('heading', 0, { id: 'stt-h', label: 'Safety Toolbox Talk', x: 48, y: 40, width: 720, fontWeight: 'bold', fontSize: 24, textAlign: 'center' }),
        createElement('divider', 0, { id: 'stt-d', x: 48, y: 90, width: 720 }),
        createElement('text-input', 0, { id: 'stt-topic', label: 'Topic', x: 48, y: 120, width: 480 }),
        createElement('date', 0, { id: 'stt-date', label: 'Date', x: 560, y: 120, width: 200 }),
        createElement('text-input', 0, { id: 'stt-presenter', label: 'Presenter Name', x: 48, y: 190, width: 340 }),
        createElement('textarea', 0, { id: 'stt-points', label: 'Discussion Points', x: 48, y: 260, width: 720, height: 120 }),
        createElement('label', 0, { id: 'stt-lbl', label: 'Attendee Signatures', x: 48, y: 400, width: 300, fontWeight: 'bold', fontSize: 16 }),
        createElement('signature', 0, { id: 'stt-sig1', label: '1.', x: 48, y: 430, width: 300 }),
        createElement('signature', 0, { id: 'stt-sig2', label: '2.', x: 380, y: 430, width: 300 }),
        createElement('signature', 0, { id: 'stt-sig3', label: '3.', x: 48, y: 510, width: 300 }),
        createElement('signature', 0, { id: 'stt-sig4', label: '4.', x: 380, y: 510, width: 300 }),
        createElement('signature', 0, { id: 'stt-sig5', label: '5.', x: 48, y: 590, width: 300 }),
        createElement('text-input', 0, { id: 'stt-next', label: 'Next Topic', x: 48, y: 680, width: 720 }),
      ],
    }),
  },
  {
    name: 'Job Hazard Analysis (JHA)',
    description: 'Task steps, associated hazards, control measures, and supervisor review',
    elementCount: 10,
    build: () => createDocument({
      title: 'Job Hazard Analysis',
      elements: [
        createElement('heading', 0, { id: 'jha-h', label: 'Job Hazard Analysis (JHA)', x: 48, y: 40, width: 720, fontWeight: 'bold', fontSize: 24, textAlign: 'center' }),
        createElement('divider', 0, { id: 'jha-d', x: 48, y: 90, width: 720 }),
        createElement('text-input', 0, { id: 'jha-job', label: 'Job / Task Name', x: 48, y: 120, width: 340 }),
        createElement('date', 0, { id: 'jha-date', label: 'Date', x: 420, y: 120, width: 200 }),
        createElement('text-input', 0, { id: 'jha-super', label: 'Supervisor', x: 48, y: 190, width: 340 }),
        createElement('text-input', 0, { id: 'jha-loc', label: 'Location', x: 420, y: 190, width: 340 }),
        createElement('table', 0, { id: 'jha-t', label: 'Hazard Analysis', x: 48, y: 270, width: 720, height: 220, tableRows: 5, tableCols: 3, tableHeaders: ['Job Step', 'Potential Hazard', 'Control Measures'] }),
        createElement('divider', 0, { id: 'jha-d2', x: 48, y: 510, width: 720 }),
        createElement('signature', 0, { id: 'jha-sig1', label: 'Prepared By', x: 48, y: 540, width: 300 }),
        createElement('signature', 0, { id: 'jha-sig2', label: 'Reviewed By', x: 400, y: 540, width: 300 }),
      ],
    }),
  },
  {
    name: 'Punch List',
    description: 'Itemized deficiencies with location, description, responsible party, and status',
    elementCount: 8,
    build: () => createDocument({
      title: 'Punch List',
      elements: [
        createElement('heading', 0, { id: 'pl-h', label: 'Punch List', x: 48, y: 40, width: 720, fontWeight: 'bold', fontSize: 24, textAlign: 'center' }),
        createElement('divider', 0, { id: 'pl-d', x: 48, y: 90, width: 720 }),
        createElement('text-input', 0, { id: 'pl-proj', label: 'Project Name', x: 48, y: 120, width: 340 }),
        createElement('date', 0, { id: 'pl-date', label: 'Date', x: 420, y: 120, width: 200 }),
        createElement('text-input', 0, { id: 'pl-contr', label: 'Contractor', x: 48, y: 190, width: 340 }),
        createElement('table', 0, { id: 'pl-t', label: 'Punch Items', x: 48, y: 260, width: 720, height: 280, tableRows: 8, tableCols: 5, tableHeaders: ['Item #', 'Location', 'Description', 'Responsible', 'Status'] }),
        createElement('divider', 0, { id: 'pl-d2', x: 48, y: 560, width: 720 }),
        createElement('signature', 0, { id: 'pl-sig', label: 'Inspector Signature', x: 48, y: 580, width: 340 }),
      ],
    }),
  },
  {
    name: 'Change Order',
    description: 'Change description, cost and schedule impact, requester and approver sign-off',
    elementCount: 11,
    build: () => createDocument({
      title: 'Change Order',
      elements: [
        createElement('heading', 0, { id: 'co-h', label: 'Change Order', x: 48, y: 40, width: 720, fontWeight: 'bold', fontSize: 24, textAlign: 'center' }),
        createElement('divider', 0, { id: 'co-d', x: 48, y: 90, width: 720 }),
        createElement('number', 0, { id: 'co-num', label: 'CO Number', x: 48, y: 120, width: 160 }),
        createElement('text-input', 0, { id: 'co-proj', label: 'Project Name', x: 240, y: 120, width: 340 }),
        createElement('date', 0, { id: 'co-date', label: 'Date', x: 610, y: 120, width: 150 }),
        createElement('textarea', 0, { id: 'co-desc', label: 'Description of Change', x: 48, y: 200, width: 720, height: 140 }),
        createElement('number', 0, { id: 'co-cost', label: 'Cost Impact', x: 48, y: 360, width: 250, numberPrefix: '$', numberDecimals: 2 }),
        createElement('text-input', 0, { id: 'co-sched', label: 'Schedule Impact', x: 330, y: 360, width: 430, placeholder: 'e.g. +5 calendar days' }),
        createElement('divider', 0, { id: 'co-d2', x: 48, y: 440, width: 720 }),
        createElement('signature', 0, { id: 'co-sig1', label: 'Requested By', x: 48, y: 470, width: 300 }),
        createElement('signature', 0, { id: 'co-sig2', label: 'Approved By', x: 400, y: 470, width: 300 }),
      ],
    }),
  },
  {
    name: 'Timesheet',
    description: 'Weekly hours by day and task with calculated total and supervisor approval',
    elementCount: 8,
    build: () => createDocument({
      title: 'Timesheet',
      elements: [
        createElement('heading', 0, { id: 'ts-h', label: 'Weekly Timesheet', x: 48, y: 40, width: 720, fontWeight: 'bold', fontSize: 24, textAlign: 'center' }),
        createElement('divider', 0, { id: 'ts-d', x: 48, y: 90, width: 720 }),
        createElement('text-input', 0, { id: 'ts-name', label: 'Employee Name', x: 48, y: 120, width: 340 }),
        createElement('date', 0, { id: 'ts-week', label: 'Week Ending', x: 420, y: 120, width: 200 }),
        createElement('table', 0, { id: 'ts-t', label: 'Hours', x: 48, y: 200, width: 720, height: 280, tableRows: 7, tableCols: 5, tableHeaders: ['Day', 'Task / Activity', 'Start Time', 'End Time', 'Hours'] }),
        createElement('calculated', 0, { id: 'ts-total', label: 'Total Hours', x: 568, y: 500, width: 200, formula: '=SUM({ts-t})', fontWeight: 'bold' }),
        createElement('divider', 0, { id: 'ts-d2', x: 48, y: 550, width: 720 }),
        createElement('signature', 0, { id: 'ts-sig', label: 'Supervisor Signature', x: 48, y: 570, width: 340 }),
      ],
    }),
  },
  {
    name: 'Concrete Pour Log',
    description: 'Mix design, slump, air content, temperature, quantity, and inspector sign-off',
    elementCount: 13,
    build: () => createDocument({
      title: 'Concrete Pour Log',
      elements: [
        createElement('heading', 0, { id: 'cpl-h', label: 'Concrete Pour Log', x: 48, y: 40, width: 720, fontWeight: 'bold', fontSize: 24, textAlign: 'center' }),
        createElement('divider', 0, { id: 'cpl-d', x: 48, y: 90, width: 720 }),
        createElement('date', 0, { id: 'cpl-date', label: 'Date', x: 48, y: 120, width: 200 }),
        createElement('text-input', 0, { id: 'cpl-loc', label: 'Location / Area', x: 280, y: 120, width: 480 }),
        createElement('text-input', 0, { id: 'cpl-mix', label: 'Mix Design', x: 48, y: 190, width: 340, placeholder: 'e.g. 4000 PSI, 3/4" agg' }),
        createElement('number', 0, { id: 'cpl-slump', label: 'Slump Test (in)', x: 420, y: 190, width: 170, numberDecimals: 1 }),
        createElement('number', 0, { id: 'cpl-air', label: 'Air Content (%)', x: 620, y: 190, width: 140, numberDecimals: 1 }),
        createElement('number', 0, { id: 'cpl-temp', label: 'Concrete Temp', x: 48, y: 260, width: 200, numberPrefix: '°F' }),
        createElement('number', 0, { id: 'cpl-qty', label: 'Quantity (CY)', x: 280, y: 260, width: 200, numberDecimals: 1 }),
        createElement('datetime', 0, { id: 'cpl-start', label: 'Start Time', x: 48, y: 330, width: 340 }),
        createElement('datetime', 0, { id: 'cpl-end', label: 'End Time', x: 420, y: 330, width: 340 }),
        createElement('divider', 0, { id: 'cpl-d2', x: 48, y: 400, width: 720 }),
        createElement('signature', 0, { id: 'cpl-sig', label: 'Inspector Signature', x: 48, y: 420, width: 340 }),
      ],
    }),
  },
  {
    name: 'Hot Work Permit',
    description: 'Work type, fire watch requirement, time window, and supervisor/fire watch signatures',
    elementCount: 12,
    build: () => createDocument({
      title: 'Hot Work Permit',
      elements: [
        createElement('heading', 0, { id: 'hwp-h', label: 'Hot Work Permit', x: 48, y: 40, width: 720, fontWeight: 'bold', fontSize: 24, textAlign: 'center' }),
        createElement('divider', 0, { id: 'hwp-d', x: 48, y: 90, width: 720 }),
        createElement('text-input', 0, { id: 'hwp-loc', label: 'Location', x: 48, y: 120, width: 480 }),
        createElement('date', 0, { id: 'hwp-date', label: 'Date', x: 560, y: 120, width: 200 }),
        createElement('radio', 0, { id: 'hwp-type', label: 'Type of Work', x: 48, y: 190, width: 300, height: 130, options: ['Welding', 'Cutting', 'Brazing', 'Other'] }),
        createElement('checkbox', 0, { id: 'hwp-fw', label: 'Fire Watch Required', x: 380, y: 190, width: 300 }),
        createElement('text-input', 0, { id: 'hwp-ext', label: 'Extinguisher Location', x: 380, y: 240, width: 380 }),
        createElement('datetime', 0, { id: 'hwp-start', label: 'Start Time', x: 48, y: 340, width: 340 }),
        createElement('datetime', 0, { id: 'hwp-end', label: 'End Time', x: 420, y: 340, width: 340 }),
        createElement('divider', 0, { id: 'hwp-d2', x: 48, y: 410, width: 720 }),
        createElement('signature', 0, { id: 'hwp-sig1', label: 'Supervisor Signature', x: 48, y: 440, width: 300 }),
        createElement('signature', 0, { id: 'hwp-sig2', label: 'Fire Watch Signature', x: 400, y: 440, width: 300 }),
      ],
    }),
  },
  {
    name: 'Equipment Inspection',
    description: 'Equipment details, 6-point checklist, notes, and inspector sign-off',
    elementCount: 14,
    build: () => createDocument({
      title: 'Equipment Inspection',
      elements: [
        createElement('heading', 0, { id: 'ei-h', label: 'Equipment Inspection', x: 48, y: 40, width: 720, fontWeight: 'bold', fontSize: 24, textAlign: 'center' }),
        createElement('divider', 0, { id: 'ei-d', x: 48, y: 90, width: 720 }),
        createElement('text-input', 0, { id: 'ei-eid', label: 'Equipment ID', x: 48, y: 120, width: 220 }),
        createElement('text-input', 0, { id: 'ei-type', label: 'Equipment Type', x: 300, y: 120, width: 220 }),
        createElement('date', 0, { id: 'ei-date', label: 'Date', x: 560, y: 120, width: 200 }),
        createElement('text-input', 0, { id: 'ei-op', label: 'Operator Name', x: 48, y: 190, width: 340 }),
        createElement('checkbox', 0, { id: 'ei-c1', label: 'Operational', x: 48, y: 260, width: 300 }),
        createElement('checkbox', 0, { id: 'ei-c2', label: 'Safety Guards in Place', x: 380, y: 260, width: 300 }),
        createElement('checkbox', 0, { id: 'ei-c3', label: 'Fluid Levels OK', x: 48, y: 300, width: 300 }),
        createElement('checkbox', 0, { id: 'ei-c4', label: 'Tires / Tracks OK', x: 380, y: 300, width: 300 }),
        createElement('checkbox', 0, { id: 'ei-c5', label: 'Lights / Signals Working', x: 48, y: 340, width: 300 }),
        createElement('checkbox', 0, { id: 'ei-c6', label: 'Fire Extinguisher Present', x: 380, y: 340, width: 300 }),
        createElement('textarea', 0, { id: 'ei-notes', label: 'Notes / Deficiencies', x: 48, y: 390, width: 720, height: 120 }),
        createElement('signature', 0, { id: 'ei-sig', label: 'Inspector Signature', x: 48, y: 530, width: 340 }),
      ],
    }),
  },
  {
    name: 'RFI (Request for Information)',
    description: 'Question, spec reference, response area, and sign-off',
    elementCount: 12,
    build: () => createDocument({
      title: 'Request for Information',
      elements: [
        createElement('heading', 0, { id: 'rfi-h', label: 'Request for Information (RFI)', x: 48, y: 40, width: 720, fontWeight: 'bold', fontSize: 24, textAlign: 'center' }),
        createElement('divider', 0, { id: 'rfi-d', x: 48, y: 90, width: 720 }),
        createElement('number', 0, { id: 'rfi-num', label: 'RFI Number', x: 48, y: 120, width: 160, numberPrefix: '#' }),
        createElement('date', 0, { id: 'rfi-date', label: 'Date', x: 240, y: 120, width: 200 }),
        createElement('text-input', 0, { id: 'rfi-from', label: 'From', x: 48, y: 190, width: 340 }),
        createElement('text-input', 0, { id: 'rfi-to', label: 'To', x: 420, y: 190, width: 340 }),
        createElement('text-input', 0, { id: 'rfi-spec', label: 'Spec Section / Drawing Ref', x: 48, y: 260, width: 720 }),
        createElement('textarea', 0, { id: 'rfi-q', label: 'Question', x: 48, y: 330, width: 720, height: 120 }),
        createElement('textarea', 0, { id: 'rfi-resp', label: 'Response', x: 48, y: 470, width: 720, height: 120 }),
        createElement('date', 0, { id: 'rfi-rdate', label: 'Response Date', x: 48, y: 610, width: 200 }),
        createElement('divider', 0, { id: 'rfi-d2', x: 48, y: 680, width: 720 }),
        createElement('signature', 0, { id: 'rfi-sig', label: 'Signature', x: 48, y: 700, width: 340 }),
      ],
    }),
  },
  {
    name: 'QCx Commissioning Report',
    description: 'Quality commissioning inspection report with observations, photos, and issue tracking',
    elementCount: 18,
    build: () => createDocument({
      title: 'QCx Commissioning Report',
      pageCount: 2,
      elements: [
        // Page 1: Project Info + Observations
        createElement('heading', 0, { id: 'qcx-h', label: 'QCx Commissioning Report', x: 48, y: 40, width: 720, fontWeight: 'bold', fontSize: 24, textAlign: 'center' }),
        createElement('divider', 0, { id: 'qcx-d1', x: 48, y: 90, width: 720 }),
        createElement('label', 0, { id: 'qcx-pi', label: 'Project Information', x: 48, y: 110, width: 300, fontWeight: 'bold', fontSize: 16 }),
        createElement('text-input', 0, { id: 'qcx-proj', label: 'Project Name', x: 48, y: 145, width: 340, required: true }),
        createElement('datetime', 0, { id: 'qcx-dt', label: 'Date / Time', x: 420, y: 145, width: 340 }),
        createElement('text-input', 0, { id: 'qcx-sys', label: 'System', x: 48, y: 215, width: 220 }),
        createElement('text-input', 0, { id: 'qcx-disc', label: 'Discipline', x: 280, y: 215, width: 220 }),
        createElement('text-input', 0, { id: 'qcx-equip', label: 'Equipment', x: 510, y: 215, width: 250 }),
        createElement('text-input', 0, { id: 'qcx-loc', label: 'Location', x: 48, y: 285, width: 720 }),
        createElement('divider', 0, { id: 'qcx-d2', x: 48, y: 345, width: 720 }),
        createElement('label', 0, { id: 'qcx-obs', label: 'Observation Details', x: 48, y: 365, width: 300, fontWeight: 'bold', fontSize: 16 }),
        createElement('textarea', 0, { id: 'qcx-detail', label: 'Observation Detail', x: 48, y: 400, width: 720, height: 120, required: true }),
        createElement('select', 0, { id: 'qcx-cat', label: 'Issue Category', x: 48, y: 540, width: 220, options: ['COR', 'NCR', 'DWN'], required: true }),
        createElement('select', 0, { id: 'qcx-stat', label: 'Issue Status', x: 280, y: 540, width: 220, options: ['Open', 'In Progress', 'Resolved', 'Closed'] }),
        createElement('textarea', 0, { id: 'qcx-action', label: 'Recommended Action', x: 510, y: 540, width: 250, height: 90 }),
        // Page 2: Photos + Signatures
        createElement('label', 1, { id: 'qcx-ph', label: 'Photo Evidence', x: 48, y: 40, width: 300, fontWeight: 'bold', fontSize: 16 }),
        createElement('photo', 1, { id: 'qcx-photos', label: 'Photos', x: 48, y: 75, width: 720, height: 500 }),
        createElement('divider', 1, { id: 'qcx-d3', x: 48, y: 600, width: 720 }),
        createElement('signature', 1, { id: 'qcx-inspsig', label: 'Inspector Signature', x: 48, y: 630, width: 340 }),
        createElement('signature', 1, { id: 'qcx-gcsig', label: 'GC Representative', x: 420, y: 630, width: 340 }),
      ],
    }),
  },
]
